# Generated by Django 4.2 on 2023-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norbitSite', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/blog_image/%Y/%m/%d/'),
        ),
    ]
