# Generated by Django 4.2 on 2023-04-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norbitSite', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_name',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='last_name',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
