# Generated by Django 4.2 on 2023-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norbitSite', '0005_post_first_name_post_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='blog_image/%Y/%m/%d/'),
        ),
    ]
