# Generated by Django 4.2 on 2023-06-08 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('norbitSite', '0007_alter_post_body_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
